### ISSUE TITLE
What exactly does this package allow me to do?

### ISSUE THREAD

**Issue by OzanKurt** [MaherSaleem/laravel-counters#1]
I believe I can already do these via Laravel.

```php
// increment/decrement model objects counters
$post->increment('number_of_views');
$feature->decrement('number_of_bugs');
$user->decrement('balance', 2); // decrement the balance of the user by 2
```

**Comment by MaherSaleem** [comment]
Hi @OzanKurt 
thanks for your comment,
first of all I have made a mistake with the methods names **( I have fixed the README.md `now)**,`
They are 
```php
// increment/decrement model objects counters\n
$post->incrementCounter('number_of_views');
$feature->decrementCounter('number_of_bugs');
$user->decrementCounter('balance', 2); // decrement the balance of the user by 2
```

The idea of this package that you don't need to create a physical column in your model's table, for example no need to create 'number_of_views' column in your Post model. That is perfect when you have many fields that are countables, suppose that a model has 10 ,which means you have to add 10 columns to your model table.

Moreover, you can here specify an initial value to reset the counter to it. In addition, your can customize the step size with every increment/decrement.

Another advantage, you can store public counters like number_of_visitors for your website, without needing to create a whole table to store it.

Best Regards

**Comment by OzanKurt** [comment]
Cool! Now it makes sense, thanks! 👍
