### ISSUE TITLE
2 files does not comply with psr-4 autoloading standard. Skipping.

### ISSUE THREAD

**Issue by RohitM-IN** [MaherSaleem/laravel-counters#4]
```
Class Maher\Counters\Models\Counter located in D:/dev/laravel/********/vendor/maher/laravel-counters/src\models\Counter.php does not comply with psr-4 autoloading standard. Skipping.
Class Maher\Counters\Models\Counterable located in D:/dev/laravel/********/vendor/maher/laravel-counters/src\models\Counterable.php does not comply with psr-4 autoloading standard. Skipping.

```

Hope this will be fixed soon

**Comment by MaherSaleem** [comment]
@RootAndroid58 thanks for reporting, I've updated the package, can you try to update yours

**Comment by RohitM-IN** [comment]
o thanks for some reason `composer require maher/laravel-counters "@dev"` even this command was installing older version or i might have missed dev portion there 
also this is an amazing package since it main point is to support non model entities for counter
