### ISSUE TITLE
How to use this package for count the number of user download ?

### ISSUE THREAD

**Issue by panggilsayabrp** [MaherSaleem/laravel-counters#6]
Hello, i have Laravel 8 project. In my project i have some features including count the number of user download. But i dont know how to implement this package for count user download.

**Comment by MaherSaleem** [comment]
Hello!
In your controller action,
you have to have something like that

```php

class YourController extends Controller
{
    public function download(YourModel $obj)
    {
        //...
        $obj->incrementCounter('downloads');
        //...
    }
}

```
let me know if you need other help!
